packages:
  - 'packages/*'
  - 'apps/*'

allowBuilds:
  '@parcel/watcher': true
  core-js: true
  esbuild: true
  vue-demi: true

onlyBuiltDependencies:
  - esbuild
  - '@parcel/watcher'
  - vue-demi
  - core-js
